### ISSUE TITLE
build failed on ubuntu 14.04.3 LTS x64

### ISSUE THREAD

**Issue by alanpurple** [christkv/kerberos#38]
> kerberos@0.0.17 install /home/alan/Repo/WindingRoad/WindingRoadBE/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/home/alan/Repo/WindingRoad/WindingRoadBE/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory `/home/alan/Repo/WindingRoad/WindingRoadBE/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/alan/Repo/WindingRoad/WindingRoadBE/node_modules/kerberos
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by codeaholics** [comment]
You need `libkrb5-dev` installed on your system.

**Comment by excalliburbd** [comment]
Try installing the Kerberos Development Package:
 ` sudo apt-get install libkrb5-dev `

**Comment by Eriatolc** [comment]
I had the same issue and installing the `libkrkb5-dev` fixed it. I am working on Kubuntu 15.04 64 bits.

**Comment by christkv** [comment]
http://mongodb.github.io/node-mongodb-native/2.1/getting-started/installation-guide/
